version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

python:
  version: 3.10
  install:
    - requirements: requirements/requirements-docs.txt
    - requirements: requirements/requirements.txt
    - method: setuptools
      path: .
