name: Unittest

on:
  push:
    branches: [ "main", "dev", "ci_improvement" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v1"
        with:
            python-version: "${{ matrix.python-version }}"
      - name: Run CI tests
        run: bash test.sh
        shell: bash
